# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  Exclude:
    - db/**/*
    - bin/*
    - lib/tasks/seed.rake
    - node_modules/**/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - config/environments/*.rb
    - spec/**/*

Metrics/LineLength:
  Max: 100
  Exclude:
    - config/initializers/secret_token.rb

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - config/boot.rb
