# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  Exclude:
    - db/**/*
    - lib/tasks/seed.rake
    - node_modules/**/*

Documentation:
  Enabled: false

# Layout/AlignHash:
  # Enabled: false

# Layout/EmptyLineAfterGuardClause:
  # Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - config/environments/*.rb
    - spec/**/*

Metrics/LineLength:
  Max: 100
  Exclude:
    # - config/initializers/content_security_policy.rb
    - config/initializers/secret_token.rb

# Style/ExpandPathArguments:
  # Enabled: false

# Style/BlockComments:
  # Enabled: false
