branch-defaults:
  amazon-switch:
    environment: huntermeyer
global:
  application_name: huntermeyer
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: null
  sc: git
